### ISSUE TITLE
error while building ( pcap.h file in gpacket/pcap dependency)

### ISSUE THREAD

**Issue by maximlomans** [domac/httpdump#1]
/httpdump$ go build -o /usr/local/var/httpdump
# github.com/google/gopacket/pcap
../../google/gopacket/pcap/pcap.go:22:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~ it's commented out
compilation terminated.

**Comment by domac** [comment]
hi, marxenegls:

I found that somethings is important in pcap.go:

line 11 ~ line 22

```
#cgo solaris LDFLAGS: -L /opt/local/lib -lpcap
#cgo linux LDFLAGS: -lpcap
#cgo dragonfly LDFLAGS: -lpcap
#cgo freebsd LDFLAGS: -lpcap
#cgo openbsd LDFLAGS: -lpcap
#cgo netbsd LDFLAGS: -lpcap
#cgo darwin LDFLAGS: -lpcap
#cgo windows CFLAGS: -I C:/WpdPack/Include
#cgo windows,386 LDFLAGS: -L C:/WpdPack/Lib -lwpcap
#cgo windows,amd64 LDFLAGS: -L C:/WpdPack/Lib/x64 -lwpcap
#include <stdlib.h>
#include <pcap.h>
```
pcap.go hardcode the lib path, so you should uninstall libpcap the reinstall it or edit the pcap.go

**Comment by maximlomans** [comment]
thanks for replying i have only just seen it ..
